import type { NextPage } from "next";
import Head from "next/head";
import { useAuthState } from "react-firebase-hooks/auth";
import Feed from "../components/Feed";
import LeftMenu from "../components/LeftMenu";
import MainContent from "../components/MainContent";
import NavBar from "../components/NavBar";
import NotUserMenu from "../components/NotUserMenu";
import PostForm from "../components/PostForm";
import RightMenu from "../components/RightMenu";
import Room from "../components/Room";
import { auth } from "../firebase/firebase";

const Home: NextPage = () => {
  const [user] = useAuthState(auth);
  return (
    <div className="bg-[#f7f7f7] dark:bg-[#18191a]">
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://clipart.info/images/ccovers/1509135366facebook-symbol-png-logo.png"
        />
      </Head>
      <NavBar />
      <section className="flex justify-center h-auto">
        <LeftMenu />
        <div className="w-full lg:w-2/3 xl:w-2/5 pt-32 lg:pt-16 px-2 ">
          {user && (
            <>
              <MainContent />
              <PostForm />
              <Room />
            </>
          )}
          <Feed />
        </div>
        {user ? <RightMenu /> : <NotUserMenu />}
      </section>
    </div>
  );
};

export default Home;
